services:
  website:
    container_name: website
    build:
      context: .
      dockerfile: Containerfile
      target: hugo
    entrypoint:
      - /usr/bin/hugo
    command:
      - server
      - --bind
      - 0.0.0.0
    develop:
      watch:
        - path: .
          action: rebuild
    ports:
      - 1313:1313
